apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: xtyu-tekton-tutorial
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xtyu
  template:
    metadata:
      name: xtyu-tekton-tutorial
      labels:
        app: xtyu
    spec:
      containers:
      - name: xtyu-tekton-tutorial
        image: __IMAGE__
